-- Create the bookings table
create table bookings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  expiry_date date,
  address text,
  client_email text,
  tenant_name text,
  tenant_phone text,
  tenant_email text,
  status text default 'lead'
);

-- Enable Row Level Security (RLS)
alter table bookings enable row level security;

-- Policy: Allow anyone to insert data (for the public booking form)
create policy "Enable insert for anon" 
on bookings 
for insert 
with check (true);

-- Policy: Allow anyone to read data (optional, useful for you to verify in dashboard if you are logged in, 
-- but typically you might want to restrict this in a real app. For now, we'll leave it open or just rely on dashboard)
create policy "Enable select for anon" 
on bookings 
for select 
using (true);
